keyboard_and_mouse_bindings:
  - key: "GLFW_KEY_W"
    callback: "camera_move_forward"
  - key: "GLFW_KEY_S"
    callback: "camera_move_backward"
    
  #- key: "GLFW_MOUSE_BUTTON_LEFT"
  #  callback: "camera_rotate"
  #- key: "GLFW_MOUSE_BUTTON_RIGHT"
  #  callback: "camera_zoom"
  - key: "LUNAR_MOUSE_SCROLL"
    callback: "camera_zoom"