# capslock and numlock are not supported
window_settings:
  title: "Lunar"
  width: 1800
  height: 1200
  isFullscreen: false

keyboard_and_mouse_settings:
  reset_mouse_position_upon_enter_window: true
keyboard_and_mouse_bindings:
  - key: "GLFW_KEY_W"
    callback: "camera_move_forward"
  - key: "GLFW_KEY_S"
    callback: "camera_move_backward"
  - key: "LUNAR_MOUSE_SCROLL"
    callback: "camera_zoom"
  - key: "GLFW_KEY_A"
    callback: "camera_move_left"
  - key: "GLFW_KEY_D"
    callback: "camera_move_right"
  - key: "GLFW_KEY_Q"
    callback: "camera_move_up"
  - key: "GLFW_KEY_E"
    callback: "camera_move_down"
  - key: "GLFW_KEY_R"
    callback: "camera_reset_zoom"
  - key: "LUNAR_MOUSE_MOVE"
    callback: "camera_rotate"
    mod: ["GLFW_MOD_CONTROL"]
  - key: "GLFW_KEY_ESCAPE"
    callback: "window_close"
  - key: "GLFW_KEY_F"
    callback: "window_fullscreen"
  - key: "GLFW_KEY_G"
    callback: "window_windowed"
