keyboard_and_mouse_settings:
  reset_mouse_position_upon_enter_window: true
keyboard_and_mouse_bindings:
  - key: "GLFW_KEY_W"
    callback: "camera_move_forward"
  - key: "GLFW_KEY_S"
    callback: "camera_move_backward"
  - key: "LUNAR_MOUSE_SCROLL"
    callback: "camera_zoom"
  - key: "GLFW_KEY_A"
    callback: "camera_move_left"
  - key: "GLFW_KEY_D"
    callback: "camera_move_right"
  - key: "LUNAR_MOUSE_MOVE"
    callback: "camera_rotate"
    mod: "GLFW_MOD_SHIFT"
